<a href="https://colab.research.google.com/github/dzhamalovas/Osnovy_programming/blob/main/%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Нахождение обратной матрицы с помощью одной формулы
В данном случае можно изменить код и ввести свои элементы матрицы. Программа автоматически найдет матрицу, обратную к данной

In [ ]:
from numpy import matrix
from numpy import linalg

In [ ]:
A = matrix( [[0,2,-1],[-1,5,-3],[-1,8,-5]]) #Создание матрицы

print (A.I)                             #Вывод обратной 


[[ 1. -2.  1.]
 [ 2.  1. -1.]
 [ 3.  2. -2.]]


# Нахождение матрицы, обратной данной
В данной программе можно ввести свою матрицу любой размерности, а программа автоматически найдет обратную 

In [ ]:
# Загрузка библиотеки
import numpy as np


row = int(input("Введите количество строк: "))  
column = int(input("Введите количество столбцов: "))  

matrix = []     # Создание пустой матрицы 
print("Построчно введите элементы матрицы: ")   # Ввод элементов матрицы
 
 
for i in range(row):        # Внешний цикл for для записей строк
   a =[]  
   for j in range(column):    # Внутренний цикл for для записей столбцов
      a.append(int(input()))  
   matrix.append(a)  
 
# Вывод исходной матрицы
for i in range(row):  
   for j in range(column):  
      print(matrix[i][j], end = " ")  
   print()  


# Нахождение и вывод обратной матрицы
arr = np.array(matrix)    # Создание одномерного массива
inverse_array = np.linalg.inv(arr)    # В NumPy обратные матрицы вычисляются с помощью функции numpy.linalg.inv(a), где a — исходная матрица.
print("Обратная матрица: ")
print(inverse_array)
print()


Введите количество строк: 2
Введите количество столбцов: 2
Построчно введите элементы матрицы: 
5
6
7
8
5 6 
7 8 
Обратная матрица: 
[[-4.   3. ]
 [ 3.5 -2.5]]



# Решение матричных уравнений A*X = B
Пользователь вводит матрицу А и В, а программа находит Х. 

In [ ]:
# Загрузка библиотеки
import numpy as np


row_a = int(input("Введите количество строк матрицы А: "))  
column_a = int(input("Введите количество столбцов матрицы А: "))  

matrix_a = []     # Создание пустой матрицы 
print("Построчно введите элементы матрицы А: ")   # Ввод элементов матрицы
 
 
for i in range(row_a):        # Внешний цикл for для записей строк
   a =[]  
   for j in range(column_a):    # Внутренний цикл for для записей столбцов
      a.append(int(input()))  
   matrix_a.append(a)  
 
# Вывод исходной матрицы
for i in range(row_a):  
   for j in range(column_a):  
      print(matrix_a[i][j], end = " ")  
   print()  

row_b = int(input("Введите количество строк матрицы В: "))  
column_b = int(input("Введите количество столбцов матрицы В: "))  

matrix_b = []     # Создание пустой матрицы 
print("Построчно введите элементы матрицы В: ")   # Ввод элементов матрицы
 
 
for i in range(row_b):        # Внешний цикл for для записей строк
   a =[]  
   for j in range(column_b):    # Внутренний цикл for для записей столбцов
      a.append(int(input()))  
   matrix_b.append(a)  
 
# Вывод исходной матрицы
for i in range(row_b):  
   for j in range(column_b):  
      print(matrix_b[i][j], end = " ") 
   print()  

# Нахождение и вывод обратной матрицы
arr = np.array(matrix_a)    # Создание одномерного массива
inverse_array = np.linalg.inv(arr)    # В NumPy обратные матрицы вычисляются с помощью функции numpy.linalg.inv(a), где a — исходная матрица.
print("Обратная матрица: ")
print(inverse_array)
print()

r = np.dot(inverse_array, matrix_b) # Функция умножения матриц
print("Х:")
print(r)

Введите количество строк матрицы А: 3
Введите количество столбцов матрицы А: 3
Построчно введите элементы матрицы А: 
1
2
3
0
1
2
0
0
1
1 2 3 
0 1 2 
0 0 1 
Введите количество строк матрицы В: 3
Введите количество столбцов матрицы В: 3
Построчно введите элементы матрицы В: 
14
11
9
8
7
4
3
2
1
14 11 9 
8 7 4 
3 2 1 
Обратная матрица: 
[[ 1. -2.  1.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]

Х:
[[ 1. -1.  2.]
 [ 2.  3.  2.]
 [ 3.  2.  1.]]
